
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
  timeout: 5000
  connect_timeout: 2
  port: 5432
  min_messages: warning


development:
  <<: *default
  database: airbnb_development

test:
  <<: *default
  database: airbnb_test

production:
  <<: *default
  database: airbnb_production
  prepared_statements: false
  advisory_locks: false
